//
//  DictionaryHTMLRenderer.swift
//  Easydict
//
//  Created by Kuroda Kayn on 2026/05/01.
//  Copyright © 2026 izual. All rights reserved.
//

import AppKit
import Foundation

// MARK: - DictionaryHTMLSection

/// Render-ready dictionary content for one result group.
///
/// Services keep ownership of lookup and resource resolution, then hand this
/// value to the shared renderer so Apple Dictionary and MDict use the same
/// result shell, details layout, and iframe escaping behavior.
struct DictionaryHTMLSection {
    let title: String
    let html: String
}

// MARK: - DictionaryHTMLRenderResult

/// Output generated by the shared dictionary HTML renderer.
///
/// The full HTML is loaded by the result WebView, while the section list keeps
/// each dictionary's rendered fragment available for existing debug-file
/// exports and future per-dictionary diagnostics.
struct DictionaryHTMLRenderResult {
    let htmlString: String
    let sections: [DictionaryHTMLSection]
}

// MARK: - DictionaryHTMLRenderer

/// Shared HTML renderer for dictionary-style services.
///
/// It owns the common `apple-dictionary.html` wrapper, entry iframe framing,
/// result colors, and details summary layout. Individual services still provide
/// already-resolved entry HTML and any service-specific CSS or JavaScript.
enum DictionaryHTMLRenderer {
    // MARK: Internal

    static func entryStyle(bodyMargin: CGFloat, extraCSS: String = "") -> String {
        let lightText = NSColor.mm_hexString(from: NSColor.ez_resultTextLight())
        let lightBG = NSColor.mm_hexString(from: NSColor.ez_resultViewBgLight())
        let darkBG = NSColor.mm_hexString(from: NSColor.ez_resultViewBgDark())

        return """
        <style>\
        body{margin:\(bodyMargin)px;color:\(lightText);background-color:\(lightBG);font-family:'system-ui';}\
        @media(prefers-color-scheme:dark){body{background-color:\(darkBG);\
        filter:invert(0.85) hue-rotate(185deg) saturate(200%) brightness(120%);}}\
        \(extraCSS)\
        </style>
        """
    }

    static func render(
        word: String,
        sections: [DictionaryHTMLSection],
        baseHTML: String? = loadBaseHTML()
    )
        -> DictionaryHTMLRenderResult? {
        let visibleSections = sections.filter {
            !$0.html.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        guard !visibleSections.isEmpty else { return nil }

        var iframesHTML = ""
        var bigWordHTML = "<h2 class=\"big-word-title\">\(word.escapedXMLString())</h2>"

        for section in visibleSections {
            let escapedHTML = section.html.escapedXMLString()
            let escapedTitle = section.title.escapedXMLString()
            let iframe = "<iframe class=\"custom-iframe-container\" srcdoc=\"\(escapedHTML)\"></iframe>"
            iframesHTML += "\(bigWordHTML)<details open><summary>\(escapedTitle)</summary>\(iframe)</details>"
            bigWordHTML = ""
        }

        let htmlString = (baseHTML ?? "<html><body></body></html>")
            .replacingOccurrences(of: "</body>", with: "\(iframesHTML)</body>")
        return DictionaryHTMLRenderResult(htmlString: htmlString, sections: visibleSections)
    }

    // MARK: Private

    private static func loadBaseHTML() -> String? {
        Bundle.main.path(forResource: "apple-dictionary", ofType: "html")
            .flatMap { try? String(contentsOfFile: $0, encoding: .utf8) }
    }
}
