name: 功能建议
description: 功能建议
title: "🚀 功能建议：{{请填写标题，不要留空}}"
labels: ["enhancement"]

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 请先确认以下事项
      options:
        - label: 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
          required: true
        - label: 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
          required: true
        - label: Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
          required: true
        - label: 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
          required: true

  - type: textarea
    id: feature_description
    attributes:
      label: 功能描述
      description: 请描述你希望的功能，有必要的话可以提供截图，以供开发者参考。
      placeholder: 功能描述
    validations:
      required: true

  - type: textarea
    id: feature_usecase
    attributes:
      label: 使用场景
      description: |
        请描述你希望功能的使用场景，有无其他类似可供参考的 App 功能等。
        如果该功能没有明确的使用场景，或是无法被开发者理解，可能会被降低优先级或忽略，因此请务必清晰描述。
      placeholder: 使用场景
    validations:
      required: true

  - type: textarea
    id: resolution
    attributes:
      label: 实现方案（可选）
      description: 对于该功能，您有什么预想的实现方案，或者建议？
      placeholder: 实现方案

  - type: checkboxes
    id: PR
    attributes:
      label: 是否愿意提交 PR 实现该功能
      description: 我们非常欢迎您提交 PR，当开发者人力不足时，提交 PR 是实现该功能的最快的方式。如果对 objc 或 Swift 语言不熟悉，可以尝试使用 ChatGPT，也许它能帮到你。
      options:
        - label: 我愿意提交 PR
