name: Bug report
description: Report an issue
title: "ðŸž Bug Report: Please fill in the title"
labels: ["bug"]
assignees:
  -

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: "Please confirm the following:"
      options:
        - label: I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
          required: true
        - label: I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
          required: true
        - label: Easydict has been upgraded to the latest version.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: Please describe the problem as clearly and detailed as possible. If it involves UI, please provide screenshots. If it's a complex problem, it would be best to provide a screencast to help developers troubleshoot. If it is an application crash issue, please provide the crash log, menu icon -> Help -> Export Log.
      placeholder: Problem description
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: Please describe how to reproduce the problem.
      placeholder:
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: Please describe the result you expect.
      placeholder:
    validations:
      required: true

  - type: textarea
    id: resolution
    attributes:
      label: Proposed solution (optional)
      description: Do you have any proposed solutions or suggestions for this issue?
      placeholder:

  - type: input
    id: device
    attributes:
      label: Device information and OS version
      description: If you encounter an unusual problem, you can provide device information and OS versions to help developers troubleshoot.
      placeholder: Apple M1 Pro, macOS 11.2.3

  - type: checkboxes
    id: PR
    attributes:
      label: Are you willing to submit a PR to fix this issue?
      description: We welcome you to submit a PR to fix this issue. When the developer is short of manpower, submitting a PR is the fastest way to solve the problem. If you are not familiar with Objective-C, you can try ChatGPT, maybe it can help you.
      options:
        - label: I'm willing to submit a PR!
