//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import "MMLog.h"
#import "EZQueryService.h"
#import "EZConstKey.h"
#import "NSString+EZChineseText.h"
#import "EZConst.h"
#import "NSImage+MM.h"
#import "NSColor+MyColors.h"
#import "entry.h"
#import "AppDelegate.h"
#import "EZLocalStorage.h"
#import "NSString+EZConvenience.h"
#import "EZWindowManager.h"
#import "NSViewController+EZWindow.h"
#import "EZLog.h"
#import "EZLanguageManager.h"
#import "DarkModeManager.h"
#import "EZNiuTransTranslate.h"
#import "EZDeepLTranslate.h"
#import "EZBingService.h"
#import "NSString+EZUtils.h"
#import "EZBaiduTranslate.h"
#import "MMCrash.h"
#import "EZDetectManager.h"
#import "EZAppleDictionary.h"
#import "EZServiceTypes.h"
#import "EZEventMonitor.h"
