//
//  CodexCLIEventParser.swift
//  Easydict
//
//  Created by long2ice on 2026/05/07.
//  Copyright © 2026 izual. All rights reserved.
//

import Foundation

// MARK: - CodexTokenUsage

/// Token usage reported in the `turn.completed` event of `codex exec --json`.
struct CodexTokenUsage {
    /// New input tokens for the current request.
    let inputTokens: Int
    /// Tokens served from the prompt cache.
    let cachedInputTokens: Int
    /// Output tokens generated by the model.
    let outputTokens: Int
    /// Reasoning output tokens (for reasoning-capable models).
    let reasoningOutputTokens: Int
    /// Wall-clock duration of the entire CLI invocation in milliseconds.
    let durationMs: Int

    /// Sum of all input-side tokens (new + cached).
    var totalInputTokens: Int {
        inputTokens + cachedInputTokens
    }

    /// Sum of all token categories.
    var totalTokens: Int {
        inputTokens + cachedInputTokens + outputTokens + reasoningOutputTokens
    }
}

// MARK: - Auth / quota detection helpers

/// Returns `true` when a message indicates Codex authentication failure.
private func isCodexAuthenticationMessage(_ message: String) -> Bool {
    let lowercased = message.lowercased()
    return lowercased.contains("not signed in")
        || lowercased.contains("not logged in")
        || lowercased.contains("please run `codex login`")
        || lowercased.contains("please run codex login")
        || lowercased.contains("authentication_failed")
        || lowercased.contains("authentication failed")
        || lowercased.contains("unauthorized")
        || lowercased.contains("not authenticated")
        || lowercased.contains("openai_api_key")
        || lowercased.contains("invalid api key")
        || lowercased.contains("401")
}

/// Returns `true` when a message indicates quota or rate-limit failure.
private func isCodexQuotaMessage(_ message: String) -> Bool {
    let lowercased = message.lowercased()
    return lowercased.contains("rate limit")
        || lowercased.contains("quota")
        || lowercased.contains("usage limit")
        || lowercased.contains("insufficient_quota")
        || lowercased.contains("insufficient quota")
        || lowercased.contains("credit")
        || lowercased.contains("429")
}

/// Extracts a human-readable message from a decoded CLI event line.
private func errorMessage(from line: CodexCLIStreamLine) -> String? {
    let candidates: [String?] = [
        line.error?.message,
        line.message,
        line.item?.error?.message,
        line.item?.message,
        line.item?.text,
    ]
    for candidate in candidates {
        if let trimmed = candidate?.trimmingCharacters(in: .whitespacesAndNewlines),
           !trimmed.isEmpty {
            return trimmed
        }
    }
    return nil
}

/// Returns `true` when an event line represents a CLI failure.
private func isFailureEvent(_ line: CodexCLIStreamLine) -> Bool {
    if line.type == "error" || line.type == "turn.failed" || line.type == "thread.failed" {
        return true
    }
    if line.type == "item.completed", line.item?.type == "error" {
        return true
    }
    return false
}

/// Parses a `CodexCLIError` by inspecting JSONL events on stdout first, then
/// falling back to stderr for plaintext failures (e.g. binary crashes).
func parseCodexError(fromStdout stdout: String, stderr: String) -> CodexCLIError {
    var stdoutAuthMessage: String?
    var stdoutQuotaMessage: String?
    var stdoutGenericMessage: String?
    let decoder = JSONDecoder()

    for line in stdout.components(separatedBy: "\n") where !line.isEmpty {
        guard let data = line.data(using: .utf8),
              let event = try? decoder.decode(CodexCLIStreamLine.self, from: data)
        else { continue }

        // Auth and quota classification only applies to terminal failure events.
        // Non-failure items (reasoning, agent_message, etc.) may legitimately mention
        // tokens like "401", "unauthorized", or "rate limit" in normal output —
        // matching them there would misclassify successful or unrelated runs.
        guard isFailureEvent(event) else { continue }
        guard let message = errorMessage(from: event) else { continue }

        if stdoutGenericMessage == nil {
            stdoutGenericMessage = message
        }
        if stdoutAuthMessage == nil, isCodexAuthenticationMessage(message) {
            stdoutAuthMessage = message
        }
        if stdoutQuotaMessage == nil, isCodexQuotaMessage(message) {
            stdoutQuotaMessage = message
        }
    }

    if stdoutAuthMessage != nil {
        return .notLoggedIn
    }
    if let stdoutQuotaMessage {
        return .quotaExceeded(message: stdoutQuotaMessage)
    }

    let cleaned = stderr
        .components(separatedBy: "\n")
        .filter { !$0.contains("MallocStackLogging") }
        .filter { !$0.contains("Reading additional input from stdin") }
        .filter { !$0.contains("Shell cwd was reset to") }
        .joined(separator: "\n")
        .trimmingCharacters(in: .whitespacesAndNewlines)

    if isCodexAuthenticationMessage(cleaned) {
        return .notLoggedIn
    }
    if isCodexQuotaMessage(cleaned) {
        return .quotaExceeded(message: nil)
    }
    if let stdoutGenericMessage, !stdoutGenericMessage.isEmpty {
        return .cliError(message: stdoutGenericMessage)
    }

    let message = cleaned.isEmpty
        ? String(localized: "service.codex_cli.cli_error.unknown")
        : cleaned
    return .cliError(message: message)
}

/// Scans stdout for the `turn.completed` event and extracts token usage.
///
/// Returns `nil` if no `turn.completed` event is found or the usage payload is empty.
/// Multiple turn.completed events may appear (one per turn); this function returns
/// the **last** parseable usage entry, which represents the cumulative final state.
func parseCodexTokenUsage(from stdout: String, durationMs: Int = 0) -> CodexTokenUsage? {
    var latestUsage: CodexTokenUsage?
    let decoder = JSONDecoder()

    for line in stdout.components(separatedBy: "\n") where !line.isEmpty {
        guard let data = line.data(using: .utf8),
              let event = try? decoder.decode(CodexCLIStreamLine.self, from: data),
              event.type == "turn.completed",
              let usage = event.usage
        else { continue }

        let hasAnyTokenField = usage.inputTokens != nil
            || usage.cachedInputTokens != nil
            || usage.outputTokens != nil
            || usage.reasoningOutputTokens != nil
        guard hasAnyTokenField else { continue }

        latestUsage = CodexTokenUsage(
            inputTokens: usage.inputTokens ?? 0,
            cachedInputTokens: usage.cachedInputTokens ?? 0,
            outputTokens: usage.outputTokens ?? 0,
            reasoningOutputTokens: usage.reasoningOutputTokens ?? 0,
            durationMs: durationMs
        )
    }
    return latestUsage
}

/// Parses one newline-delimited JSON line from `codex exec --json` output and
/// returns the assistant text when the event is an `item.completed` carrying an
/// `agent_message`.
///
/// Codex 0.128.x does not stream text deltas — it emits the full message text in
/// a single `item.completed` event per turn. Other events (`thread.started`,
/// `turn.started`, `turn.completed`, reasoning items, …) return `nil`.
///
/// - Parameter decoder: Caller-supplied decoder to avoid per-call allocation on the hot path.
func extractCodexText(from line: String, decoder: JSONDecoder = JSONDecoder()) -> String? {
    guard let data = line.data(using: .utf8),
          let event = try? decoder.decode(CodexCLIStreamLine.self, from: data),
          event.type == "item.completed",
          event.item?.type == "agent_message",
          let text = event.item?.text,
          !text.isEmpty
    else { return nil }
    return text
}

// MARK: - CodexCLIStreamLine

/// One newline-delimited event from `codex exec --json`.
///
/// Codex 0.128.x event types observed:
/// - `thread.started` — session opened, carries `thread_id`.
/// - `turn.started` — agent turn began.
/// - `item.completed` — one item finished. The `item.type` distinguishes
///   `agent_message` (carries `text`) from other items such as `reasoning`.
/// - `turn.completed` — turn finished, carries `usage`.
/// - `turn.failed` / `thread.failed` / `error` — failure events (treated optimistically).
private struct CodexCLIStreamLine: Decodable {
    let type: String
    /// Set on `item.completed` events.
    let item: CodexCLIItem?
    /// Set on `turn.completed` events.
    let usage: CodexCLIRawUsage?
    /// Set on top-level `error` / `turn.failed` events. Codex emits this field
    /// either as a string or as a structured object such as
    /// `{"message":"...","code":"..."}`, so a flexible decoder is required.
    let error: CodexCLIErrorField?
    /// Free-form message field that some failure events carry at the top level.
    let message: String?
}

// MARK: - CodexCLIItem

/// One completed item inside an `item.completed` event.
private struct CodexCLIItem: Decodable {
    let id: String?
    /// Item kind, e.g. `agent_message`, `reasoning`, `error`.
    let type: String
    /// Set on `agent_message` items.
    let text: String?
    /// Set on `error` items. Same flexible string-or-object shape as the
    /// top-level `error` field.
    let error: CodexCLIErrorField?
    /// Free-form message field used by some item kinds.
    let message: String?
}

// MARK: - CodexCLIErrorField

/// Decodes the polymorphic `error` field that Codex emits on failure events.
///
/// Codex 0.128.x writes the field either as a plain string
/// (`"error":"Not signed in"`) or as a structured object
/// (`"error":{"message":"…","code":"…","type":"…"}`). Strict `String?`
/// decoding silently drops the structured form and loses the only actionable
/// failure information on stdout, so this wrapper accepts both shapes and
/// extracts a best-effort `message`.
private struct CodexCLIErrorField: Decodable {
    // MARK: Lifecycle

    init(from decoder: Decoder) throws {
        // 1) Plain string form: `"error":"text"`.
        let single = try decoder.singleValueContainer()
        if let asString = try? single.decode(String.self) {
            self.message = asString
            return
        }

        // 2) Structured object form: try common message-bearing keys.
        if let keyed = try? decoder.container(keyedBy: ObjectKey.self) {
            let candidateKeys: [ObjectKey] = [.message, .error, .description, .detail]
            for key in candidateKeys {
                if let value = try? keyed.decode(String.self, forKey: key),
                   !value.isEmpty {
                    self.message = value
                    return
                }
            }
        }

        // 3) Anything else (number, array, null) — fail soft.
        self.message = nil
    }

    // MARK: Internal

    let message: String?

    // MARK: Private

    private enum ObjectKey: String, CodingKey {
        case message, error, description, detail
    }
}

// MARK: - CodexCLIRawUsage

/// Raw usage fields emitted on `turn.completed`. All optional — the CLI may
/// omit fields when the model does not produce reasoning tokens, etc.
private struct CodexCLIRawUsage: Decodable {
    enum CodingKeys: String, CodingKey {
        case inputTokens = "input_tokens"
        case cachedInputTokens = "cached_input_tokens"
        case outputTokens = "output_tokens"
        case reasoningOutputTokens = "reasoning_output_tokens"
    }

    let inputTokens: Int?
    let cachedInputTokens: Int?
    let outputTokens: Int?
    let reasoningOutputTokens: Int?
}
