name: issue-translator

on:
  issue_comment:
    types: [ created ]
  issues:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: tisfeng/issues-translate-action@v2.9.0
        with:
          IS_MODIFY_TITLE: false
          PRIMARY_LANGUAGE: zh-CN
          SECONDARY_LANGUAGE: en
          CUSTOM_BOT_NOTE: Bot automatically translated this content.
